export const GET_GOODS_DATA = 'GET_GOODS_DATA'; // 获取商品数据
export const GET_GOODS_DETAIL_EVALUATE_LIST = 'GET_GOODS_DETAIL_EVALUATE_LIST'; // 获取商品详情评价数据
export const GOODS_COLLECT_ISDONE = 'GOODS_COLLECT_ISDONE'; // 商品收藏
