export const GET_MALL_ADDRESS_LIST_DATA = 'GET_MALL_ADDRESS_LIST_DATA'; // 获取收货地址列表
export const GET_MALL_ADDRESS_DEFAULT_DATA = 'GET_MALL_ADDRESS_DEFAULT_DATA'; // 获取默认收货地址数据
export const GET_MALL_ADDRESS_DETAIL = 'GET_MALL_ADDRESS_DETAIL'; // 获取某收货地址详情
export const GET_MALL_ORDER_DETAIL_DATA = 'GET_MALL_ORDER_DETAIL_DATA'; // 获取订单详情
export const GET_MALL_HOT_SEARCH_DATA = 'GET_MALL_HOT_SEARCH_DATA'; // 获取热门搜索关键词
export const GET_MALL_EVALUATE_DETAIL_DATA = 'GET_MALL_EVALUATE_DETAIL_DATA'; // 获取评价详情
export const GET_MALL_MERGE_ORDER_CONDITION_DATA = 'GET_MALL_MERGE_ORDER_CONDITION_DATA'; // 获取凑单分类
export const GET_MALL_REFUND_REASON_DATA = 'GET_MALL_REFUND_REASON_DATA'; // 获取退款原因
